# Generated by Django 4.1.4 on 2023-01-31 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_mark_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='Total_mark',
        ),
        migrations.AlterField(
            model_name='mark',
            name='Total',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='biology',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='chemistry',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='english',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='maths',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='physics',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
