# Generated by Django 4.1.4 on 2023-01-31 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_remove_mark_total_mark_alter_mark_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='Total',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(250)]),
        ),
    ]
